target_detector_node:
  ros__parameters:
    mode: color

    input_image_topic: /recognition/preprocessed/image
    input_mask_topic: /recognition/preprocessed/mask

    target_topic: /recognition/target
    debug_image_topic: /recognition/detection/debug_image
    publish_debug_image: true

    mask_max_age_sec: 0.3

    color_use_mask_topic: true
    color_fallback_to_hsv: true
    color_min_area: 300.0

    color_lower_h_1: 0
    color_upper_h_1: 10
    color_lower_h_2: 170
    color_upper_h_2: 180
    color_lower_s: 120
    color_lower_v: 70
    color_upper_s: 255
    color_upper_v: 255